# Feature Selection Strategy

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [31]:
df = pd.read_csv("../data/mergedTrialData.csv.gz")
df.head()

,subject,trial,condition,ITI,rejected,Fz_N100,FCz_N100,Cz_N100,FC3_N100,FC4_N100,...,CP4_B0,Fz_B1,FCz_B1,Cz_B1,FC3_B1,FC4_B1,C3_B1,C4_B1,CP3_B1,CP4_B1
0,1,1,1,NaN,0,-9.761338,-11.545219,-16.775214,-3.576595,-11.745167,...,-0.005642,-14.815963,-23.173850,-25.626646,-13.285282,-23.223037,-23.622596,-19.071931,-19.529142,-26.677147
1,1,2,1,2025.3906,0,8.717519,11.462619,7.979110,9.429738,6.912862,...,0.066728,19.337457,18.359870,15.224155,13.442292,16.981404,11.953868,10.168470,5.831319,6.503993
2,1,3,1,2303.7109,0,-4.027286,-3.992038,-1.104119,-3.319471,0.321314,...,0.011351,5.443106,1.081921,0.316871,1.199502,0.929950,1.343815,3.131847,3.691148,0.338882
3,1,4,1,2275.3906,0,0.394095,-0.663186,-1.372871,3.974643,-1.613667,...,0.010070,5.417850,3.702130,7.823421,5.336565,-0.448384,7.983687,6.579145,8.474662,9.381523
4,1,5,1,2464.8438,0,-9.368090,-12.029829,-10.280100,-7.846471,-8.170986,...,-0.082809,-6.464376,-6.817497,-6.286747,0.212776,-5.815893,2.517058,-1.101036,-4.325141,-4.832745

In [35]:
df['rejected'] = df['rejected'].astype('category')
df['condition'] = df['condition'].astype('category')

df.dtypes

subject         int64
trial           int64
condition    category
ITI           float64
rejected     category
Fz_N100       float64
FCz_N100      float64
Cz_N100       float64
FC3_N100      float64
FC4_N100      float64
C3_N100       float64
C4_N100       float64
CP3_N100      float64
CP4_N100      float64
Fz_P200       float64
FCz_P200      float64
Cz_P200       float64
FC3_P200      float64
FC4_P200      float64
C3_P200       float64
C4_P200       float64
CP3_P200      float64
CP4_P200      float64
Fz_B0         float64
FCz_B0        float64
Cz_B0         float64
FC3_B0        float64
FC4_B0        float64
C3_B0         float64
C4_B0         float64
CP3_B0        float64
CP4_B0        float64
Fz_B1         float64
FCz_B1        float64
Cz_B1         float64
FC3_B1        float64
FC4_B1        float64
C3_B1         float64
C4_B1         float64
CP3_B1        float64
CP4_B1        float64
dtype: object

In [43]:
varSel = pd.DataFrame({'Variable': df.columns[5:41]})
varSel.head()

   Variable
0   Fz_N100
1  FCz_N100
2   Cz_N100
3  FC3_N100
4  FC4_N100

## Univariable Analysis

In [17]:
from importlib import reload
import pyTable1 as tb1
reload(tb1)

In [36]:
tab1 = tb1.pyMechkar.Table1(x=df.columns[5:41], y="condition", data=df)

Factorizing... please wait
[************************************
[]
*****************************************
*****************************************
*****************************************
[]
------ Finished in 20.739538431167603econds -----

In [37]:
tab1

,Variables,Categories,Population,Category_1,Category_2,Category_3,p_value
0,Individuals,n,23986,8089,7929,7968,NaN
1,Fz_N100,Mean (SD),-2.60 ( 11.30),-3.30 ( 11.70),-4.50 ( 10.90),0.10 ( 10.80),0.000
2,Fz_N100,Median (IQR),-2.60 ( -8.80- 3.50),-3.30 ( -9.60- 2.50),-4.40 ( -10.50- 1.60),-0.10 ( -5.90- 5.70),0.000
3,Fz_N100,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
4,FCz_N100,Mean (SD),-2.70 ( 11.30),-3.30 ( 11.40),-5.00 ( 11.20),0.20 ( 10.70),0.000
5,FCz_N100,Median (IQR),-2.60 ( -9.20- 3.80),-3.20 ( -9.90- 3.00),-4.80 ( -11.40- 1.50),0.10 ( -5.90- 6.30),0.000
6,FCz_N100,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
7,Cz_N100,Mean (SD),-2.10 ( 11.10),-2.50 ( 11.10),-4.70 ( 11.10),0.80 ( 10.50),0.000
8,Cz_N100,Median (IQR),-2.00 ( -8.60- 4.40),-2.30 ( -9.00- 3.80),-4.50 ( -11.00- 1.70),0.70 ( -5.40- 6.70),0.000
9,Cz_N100,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
10,FC3_N100,Mean (SD),-2.00 ( 10.20),-2.60 ( 10.30),-4.20 ( 10.00),0.70 ( 9.50),0.000
11,FC3_N100,Median (IQR),-2.00 ( -7.60- 3.70),-2.50 ( -8.10- 3.00),-4.20 ( -9.80- 1.50),0.50 ( -4.70- 5.80),0.000
12,FC3_N100,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
13,FC4_N100,Mean (SD),-2.30 ( 10.30),-3.00 ( 10.50),-4.20 ( 10.10),0.30 ( 9.60),0.000
14,FC4_N100,Median (IQR),-2.30 ( -8.00- 3.40),-3.00 ( -8.70- 2.60),-4.10 ( -9.80- 1.50),0.10 ( -5.20- 5.70),0.000
15,FC4_N100,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
16,C3_N100,Mean (SD),-1.50 ( 9.90),-1.90 ( 9.80),-4.00 ( 9.80),1.40 ( 9.20),0.000
17,C3_N100,Median (IQR),-1.40 ( -7.10- 4.10),-1.80 ( -7.40- 3.60),-4.00 ( -9.50- 1.50),1.30 ( -3.80- 6.50),0.000
18,C3_N100,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
19,C4_N100,Mean (SD),-2.00 ( 9.90),-2.50 ( 9.90),-3.90 ( 9.80),0.40 ( 9.40),0.000
20,C4_N100,Median (IQR),-2.00 ( -7.70- 3.60),-2.60 ( -8.20- 3.00),-3.80 ( -9.50- 1.80),0.40 ( -4.90- 5.80),0.000
21,C4_N100,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
22,CP3_N100,Mean (SD),-1.10 ( 10.10),-1.50 ( 10.00),-3.40 ( 10.30),1.40 ( 9.50),0.000
23,CP3_N100,Median (IQR),-1.10 ( -6.90- 4.70),-1.50 ( -7.20- 4.30),-3.20 ( -9.00- 2.40),1.30 ( -3.90- 6.70),0.000
24,CP3_N100,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
25,CP4_N100,Mean (SD),-1.50 ( 10.30),-1.90 ( 10.50),-3.10 ( 10.30),0.40 ( 9.90),0.000
26,CP4_N100,Median (IQR),-1.60 ( -7.40- 4.30),-2.20 ( -7.80- 4.00),-3.20 ( -8.90- 2.80),0.40 ( -5.20- 6.00),0.000
27,CP4_N100,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
28,Fz_P200,Mean (SD),3.00 ( 12.20),3.90 ( 12.90),3.30 ( 11.80),1.70 ( 11.70),0.000
29,Fz_P200,Median (IQR),2.50 ( -3.70- 9.10),3.40 ( -3.00- 10.10),2.90 ( -3.20- 9.50),1.40 ( -4.70- 7.50),0.000
...,...,...,...,...,...,...,...
79,CP4_B0,Mean (SD),0.00 ( 0.10),0.00 ( 0.10),0.00 ( 0.10),0.00 ( 0.10),0.113
80,CP4_B0,Median (IQR),0.00 ( -0.00- 0.00),0.00 ( -0.00- 0.00),0.00 ( -0.00- 0.00),0.00 ( -0.00- 0.00),0.113
81,CP4_B0,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
82,Fz_B1,Mean (SD),0.30 ( 13.20),0.60 ( 14.20),0.10 ( 13.10),0.40 ( 12.10),0.065
83,Fz_B1,Median (IQR),0.50 ( -6.20- 7.00),0.70 ( -6.00- 7.40),0.30 ( -6.40- 6.70),0.30 ( -6.20- 6.80),0.065
84,Fz_B1,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
85,FCz_B1,Mean (SD),0.60 ( 12.00),0.90 ( 12.20),0.10 ( 12.00),0.90 ( 11.60),0.000
86,FCz_B1,Median (IQR),0.70 ( -6.10- 7.40),1.00 ( -5.90- 7.80),0.20 ( -6.40- 6.80),0.80 ( -5.90- 7.50),0.000
87,FCz_B1,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
88,Cz_B1,Mean (SD),0.80 ( 11.40),1.00 ( 11.40),0.20 ( 11.50),1.10 ( 11.30),0.000
89,Cz_B1,Median (IQR),0.80 ( -5.70- 7.50),1.20 ( -5.40- 7.80),0.20 ( -6.30- 6.80),1.10 ( -5.50- 7.70),0.000
90,Cz_B1,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
91,FC3_B1,Mean (SD),0.70 ( 11.80),1.10 ( 12.10),0.10 ( 12.10),0.80 ( 11.00),0.000
92,FC3_B1,Median (IQR),0.60 ( -5.30- 6.90),1.20 ( -5.00- 7.50),0.10 ( -5.80- 6.30),0.70 ( -5.20- 6.80),0.000
93,FC3_B1,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
94,FC4_B1,Mean (SD),0.40 ( 11.90),0.40 ( 12.10),0.30 ( 12.30),0.40 ( 11.10),0.752
95,FC4_B1,Median (IQR),0.40 ( -5.80- 6.60),0.60 ( -5.60- 6.70),0.40 ( -5.90- 6.60),0.30 ( -5.80- 6.50),0.752
96,FC4_B1,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
97,C3_B1,Mean (SD),0.80 ( 10.70),1.10 ( 11.00),0.20 ( 10.80),1.10 ( 10.30),0.000
98,C3_B1,Median (IQR),0.80 ( -5.00- 6.80),1.00 ( -4.60- 7.30),0.30 ( -5.60- 6.30),1.10 ( -4.80- 7.00),0.000
99,C3_B1,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
100,C4_B1,Mean (SD),0.40 ( 10.80),0.50 ( 11.00),0.30 ( 10.80),0.40 ( 10.50),0.439
101,C4_B1,Median (IQR),0.40 ( -5.50- 6.50),0.70 ( -5.40- 6.80),0.40 ( -5.60- 6.20),0.30 ( -5.60- 6.30),0.439
102,C4_B1,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
103,CP3_B1,Mean (SD),0.60 ( 10.70),0.70 ( 10.80),0.20 ( 10.80),0.90 ( 10.50),0.000
104,CP3_B1,Median (IQR),0.70 ( -5.20- 6.70),0.70 ( -5.00- 6.90),0.30 ( -5.50- 6.40),0.90 ( -4.90- 6.90),0.000
105,CP3_B1,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN
106,CP4_B1,Mean (SD),0.40 ( 11.30),0.40 ( 11.80),0.40 ( 11.40),0.30 ( 10.60),0.769
107,CP4_B1,Median (IQR),0.50 ( -5.60- 6.50),0.70 ( -5.50- 6.70),0.50 ( -5.60- 6.60),0.30 ( -5.60- 6.20),0.769
108,CP4_B1,Missing (%),785.00 ( 3.30%),253.00 ( 3.10%),298.00 ( 3.80%),234.00 ( 2.90%),NaN

In [40]:
tab1[tab1['p_value']<0.05]

,Variables,Categories,Population,Category_1,Category_2,Category_3,p_value
1,Fz_N100,Mean (SD),-2.60 ( 11.30),-3.30 ( 11.70),-4.50 ( 10.90),0.10 ( 10.80),0.000
2,Fz_N100,Median (IQR),-2.60 ( -8.80- 3.50),-3.30 ( -9.60- 2.50),-4.40 ( -10.50- 1.60),-0.10 ( -5.90- 5.70),0.000
4,FCz_N100,Mean (SD),-2.70 ( 11.30),-3.30 ( 11.40),-5.00 ( 11.20),0.20 ( 10.70),0.000
5,FCz_N100,Median (IQR),-2.60 ( -9.20- 3.80),-3.20 ( -9.90- 3.00),-4.80 ( -11.40- 1.50),0.10 ( -5.90- 6.30),0.000
7,Cz_N100,Mean (SD),-2.10 ( 11.10),-2.50 ( 11.10),-4.70 ( 11.10),0.80 ( 10.50),0.000
8,Cz_N100,Median (IQR),-2.00 ( -8.60- 4.40),-2.30 ( -9.00- 3.80),-4.50 ( -11.00- 1.70),0.70 ( -5.40- 6.70),0.000
10,FC3_N100,Mean (SD),-2.00 ( 10.20),-2.60 ( 10.30),-4.20 ( 10.00),0.70 ( 9.50),0.000
11,FC3_N100,Median (IQR),-2.00 ( -7.60- 3.70),-2.50 ( -8.10- 3.00),-4.20 ( -9.80- 1.50),0.50 ( -4.70- 5.80),0.000
13,FC4_N100,Mean (SD),-2.30 ( 10.30),-3.00 ( 10.50),-4.20 ( 10.10),0.30 ( 9.60),0.000
14,FC4_N100,Median (IQR),-2.30 ( -8.00- 3.40),-3.00 ( -8.70- 2.60),-4.10 ( -9.80- 1.50),0.10 ( -5.20- 5.70),0.000
16,C3_N100,Mean (SD),-1.50 ( 9.90),-1.90 ( 9.80),-4.00 ( 9.80),1.40 ( 9.20),0.000
17,C3_N100,Median (IQR),-1.40 ( -7.10- 4.10),-1.80 ( -7.40- 3.60),-4.00 ( -9.50- 1.50),1.30 ( -3.80- 6.50),0.000
19,C4_N100,Mean (SD),-2.00 ( 9.90),-2.50 ( 9.90),-3.90 ( 9.80),0.40 ( 9.40),0.000
20,C4_N100,Median (IQR),-2.00 ( -7.70- 3.60),-2.60 ( -8.20- 3.00),-3.80 ( -9.50- 1.80),0.40 ( -4.90- 5.80),0.000
22,CP3_N100,Mean (SD),-1.10 ( 10.10),-1.50 ( 10.00),-3.40 ( 10.30),1.40 ( 9.50),0.000
23,CP3_N100,Median (IQR),-1.10 ( -6.90- 4.70),-1.50 ( -7.20- 4.30),-3.20 ( -9.00- 2.40),1.30 ( -3.90- 6.70),0.000
25,CP4_N100,Mean (SD),-1.50 ( 10.30),-1.90 ( 10.50),-3.10 ( 10.30),0.40 ( 9.90),0.000
26,CP4_N100,Median (IQR),-1.60 ( -7.40- 4.30),-2.20 ( -7.80- 4.00),-3.20 ( -8.90- 2.80),0.40 ( -5.20- 6.00),0.000
28,Fz_P200,Mean (SD),3.00 ( 12.20),3.90 ( 12.90),3.30 ( 11.80),1.70 ( 11.70),0.000
29,Fz_P200,Median (IQR),2.50 ( -3.70- 9.10),3.40 ( -3.00- 10.10),2.90 ( -3.20- 9.50),1.40 ( -4.70- 7.50),0.000
31,FCz_P200,Mean (SD),3.60 ( 11.80),4.80 ( 12.20),3.90 ( 11.90),2.10 ( 11.30),0.000
32,FCz_P200,Median (IQR),3.20 ( -3.20- 10.10),4.50 ( -2.30- 11.50),3.60 ( -2.80- 10.40),1.80 ( -4.50- 8.30),0.000
34,Cz_P200,Mean (SD),3.80 ( 11.40),5.00 ( 11.60),3.90 ( 11.60),2.30 ( 10.90),0.000
35,Cz_P200,Median (IQR),3.40 ( -2.90- 10.20),4.70 ( -1.70- 11.60),3.70 ( -2.70- 10.40),1.90 ( -4.10- 8.40),0.000
37,FC3_P200,Mean (SD),3.20 ( 10.80),4.20 ( 11.40),3.20 ( 10.70),2.20 ( 10.30),0.000
38,FC3_P200,Median (IQR),3.00 ( -2.90- 8.90),3.90 ( -2.10- 10.00),2.90 ( -2.70- 8.80),2.00 ( -3.70- 7.70),0.000
40,FC4_P200,Mean (SD),2.70 ( 10.90),3.50 ( 11.40),3.30 ( 10.90),1.50 ( 10.30),0.000
41,FC4_P200,Median (IQR),2.40 ( -3.30- 8.40),3.20 ( -2.70- 9.30),2.90 ( -2.80- 9.10),1.20 ( -4.50- 7.00),0.000
43,C3_P200,Mean (SD),3.40 ( 10.20),4.50 ( 10.60),3.20 ( 10.20),2.50 ( 9.70),0.000
44,C3_P200,Median (IQR),3.20 ( -2.50- 9.10),4.20 ( -1.50- 10.40),3.00 ( -2.70- 8.90),2.30 ( -3.10- 7.80),0.000
46,C4_P200,Mean (SD),2.60 ( 10.20),3.40 ( 10.40),3.20 ( 10.20),1.30 ( 9.70),0.000
47,C4_P200,Median (IQR),2.40 ( -3.30- 8.30),3.40 ( -2.60- 9.10),2.90 ( -2.70- 8.80),1.10 ( -4.40- 6.80),0.000
49,CP3_P200,Mean (SD),2.70 ( 10.30),3.60 ( 10.60),2.70 ( 10.30),1.90 ( 9.80),0.000
50,CP3_P200,Median (IQR),2.50 ( -3.20- 8.40),3.50 ( -2.40- 9.50),2.50 ( -3.20- 8.50),1.70 ( -3.90- 7.40),0.000
52,CP4_P200,Mean (SD),2.10 ( 10.50),2.90 ( 10.80),2.60 ( 10.40),1.00 ( 10.00),0.000
53,CP4_P200,Median (IQR),2.00 ( -3.90- 7.90),2.80 ( -3.20- 8.70),2.40 ( -3.40- 8.40),0.90 ( -4.90- 6.50),0.000
55,Fz_B0,Mean (SD),-0.00 ( 0.10),-0.00 ( 0.10),0.00 ( 0.10),-0.00 ( 0.10),0.000
56,Fz_B0,Median (IQR),-0.00 ( -0.10- 0.00),-0.00 ( -0.10- 0.00),-0.00 ( -0.00- 0.00),-0.00 ( -0.10- 0.00),0.000
58,FCz_B0,Mean (SD),-0.00 ( 0.10),-0.00 ( 0.10),0.00 ( 0.10),-0.00 ( 0.10),0.000
59,FCz_B0,Median (IQR),-0.00 ( -0.10- 0.00),-0.00 ( -0.10- 0.00),0.00 ( -0.10- 0.10),-0.00 ( -0.10- 0.00),0.000
64,FC3_B0,Mean (SD),-0.00 ( 0.10),-0.00 ( 0.10),-0.00 ( 0.10),-0.00 ( 0.10),0.015
65,FC3_B0,Median (IQR),-0.00 ( -0.00- 0.00),-0.00 ( -0.00- 0.00),-0.00 ( -0.00- 0.00),-0.00 ( -0.00- 0.00),0.015
67,FC4_B0,Mean (SD),-0.00 ( 0.10),-0.00 ( 0.10),0.00 ( 0.10),-0.00 ( 0.10),0.023
68,FC4_B0,Median (IQR),-0.00 ( -0.00- 0.00),-0.00 ( -0.00- 0.00),0.00 ( -0.00- 0.00),-0.00 ( -0.00- 0.00),0.023
76,CP3_B0,Mean (SD),0.00 ( 0.10),0.00 ( 0.10),-0.00 ( 0.10),0.00 ( 0.10),0.000
77,CP3_B0,Median (IQR),0.00 ( -0.00- 0.00),0.00 ( -0.00- 0.10),-0.00 ( -0.00- 0.00),0.00 ( -0.00- 0.00),0.000
85,FCz_B1,Mean (SD),0.60 ( 12.00),0.90 ( 12.20),0.10 ( 12.00),0.90 ( 11.60),0.000
86,FCz_B1,Median (IQR),0.70 ( -6.10- 7.40),1.00 ( -5.90- 7.80),0.20 ( -6.40- 6.80),0.80 ( -5.90- 7.50),0.000
88,Cz_B1,Mean (SD),0.80 ( 11.40),1.00 ( 11.40),0.20 ( 11.50),1.10 ( 11.30),0.000
89,Cz_B1,Median (IQR),0.80 ( -5.70- 7.50),1.20 ( -5.40- 7.80),0.20 ( -6.30- 6.80),1.10 ( -5.50- 7.70),0.000
91,FC3_B1,Mean (SD),0.70 ( 11.80),1.10 ( 12.10),0.10 ( 12.10),0.80 ( 11.00),0.000
92,FC3_B1,Median (IQR),0.60 ( -5.30- 6.90),1.20 ( -5.00- 7.50),0.10 ( -5.80- 6.30),0.70 ( -5.20- 6.80),0.000
97,C3_B1,Mean (SD),0.80 ( 10.70),1.10 ( 11.00),0.20 ( 10.80),1.10 ( 10.30),0.000
98,C3_B1,Median (IQR),0.80 ( -5.00- 6.80),1.00 ( -4.60- 7.30),0.30 ( -5.60- 6.30),1.10 ( -4.80- 7.00),0.000
103,CP3_B1,Mean (SD),0.60 ( 10.70),0.70 ( 10.80),0.20 ( 10.80),0.90 ( 10.50),0.000
104,CP3_B1,Median (IQR),0.70 ( -5.20- 6.70),0.70 ( -5.00- 6.90),0.30 ( -5.50- 6.40),0.90 ( -4.90- 6.90),0.000

In [42]:
vn1 = tab1.loc[tab1['p_value']<0.05,'Variables'].unique()
print(len(vn1))
vn1

28

array(['Fz_N100', 'FCz_N100', 'Cz_N100', 'FC3_N100', 'FC4_N100',
       'C3_N100', 'C4_N100', 'CP3_N100', 'CP4_N100', 'Fz_P200',
       'FCz_P200', 'Cz_P200', 'FC3_P200', 'FC4_P200', 'C3_P200',
       'C4_P200', 'CP3_P200', 'CP4_P200', 'Fz_B0', 'FCz_B0', 'FC3_B0',
       'FC4_B0', 'CP3_B0', 'FCz_B1', 'Cz_B1', 'FC3_B1', 'C3_B1', 'CP3_B1'],
      dtype=object)

We will add these variables to our variable selection table

In [48]:
varSel['Univarable'] = 0
varSel.loc[varSel['Variable'].isin(vn1), 'Univarable'] = 1
varSel

    Variable  Univarable
0    Fz_N100           1
1   FCz_N100           1
2    Cz_N100           1
3   FC3_N100           1
4   FC4_N100           1
5    C3_N100           1
6    C4_N100           1
7   CP3_N100           1
8   CP4_N100           1
9    Fz_P200           1
10  FCz_P200           1
11   Cz_P200           1
12  FC3_P200           1
13  FC4_P200           1
14   C3_P200           1
15   C4_P200           1
16  CP3_P200           1
17  CP4_P200           1
18     Fz_B0           1
19    FCz_B0           1
20     Cz_B0           0
21    FC3_B0           1
22    FC4_B0           1
23     C3_B0           0
24     C4_B0           0
25    CP3_B0           1
26    CP4_B0           0
27     Fz_B1           0
28    FCz_B1           1
29     Cz_B1           1
30    FC3_B1           1
31    FC4_B1           0
32     C3_B1           1
33     C4_B1           0
34    CP3_B1           1
35    CP4_B1           0

## Multivariable Analysis

In [59]:
### drop na
df = df.dropna()

In [60]:
## remove unnecessary vars
X = df.loc[:,df.columns[5:41]]
X.head()

,Fz_N100,FCz_N100,Cz_N100,FC3_N100,FC4_N100,C3_N100,C4_N100,CP3_N100,CP4_N100,Fz_P200,...,CP4_B0,Fz_B1,FCz_B1,Cz_B1,FC3_B1,FC4_B1,C3_B1,C4_B1,CP3_B1,CP4_B1
1,8.717519,11.462619,7.979110,9.429738,6.912862,6.242343,4.690100,2.795200,1.938529,6.607412,...,0.066728,19.337457,18.359870,15.224155,13.442292,16.981404,11.953868,10.168470,5.831319,6.503993
2,-4.027286,-3.992038,-1.104119,-3.319471,0.321314,0.419538,0.030619,2.828195,2.731533,11.485566,...,0.011351,5.443106,1.081921,0.316871,1.199502,0.929950,1.343815,3.131847,3.691148,0.338882
3,0.394095,-0.663186,-1.372871,3.974643,-1.613667,2.376024,-1.504500,2.945000,-1.082224,11.772395,...,0.010070,5.417850,3.702130,7.823421,5.336565,-0.448384,7.983687,6.579145,8.474662,9.381523
4,-9.368090,-12.029829,-10.280100,-7.846471,-8.170986,-10.192229,-6.907095,-14.041000,-9.666710,3.829656,...,-0.082809,-6.464376,-6.817497,-6.286747,0.212776,-5.815893,2.517058,-1.101036,-4.325141,-4.832745
5,-10.790257,-10.572367,-14.636533,-9.880271,-15.229224,-14.060162,-14.101090,-15.782033,-12.055395,-0.335049,...,0.054572,2.653335,4.611185,10.518641,1.485885,5.749364,9.621524,7.304800,7.605020,10.287658

In [61]:
y = df.loc[:,df.columns[2]]
print([X.shape,y.shape])

[(23006, 36), (23006,)]

### Variable Selection using LASSO (L1 penalization)

In [97]:
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel

lassomod = Lasso(alpha=0.01).fit(X, y)

In [98]:
model = SelectFromModel(lassomod, prefit=True)
model.get_support()

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True, False,  True,  True, False])

In [99]:
varSel['Lasso'] = model.get_support().astype('int64')
varSel

    Variable  Univarable  RandomForest  Lasso
0    Fz_N100           1             1      1
1   FCz_N100           1             1      0
2    Cz_N100           1             1      1
3   FC3_N100           1             1      1
4   FC4_N100           1             1      1
5    C3_N100           1             1      1
6    C4_N100           1             1      1
7   CP3_N100           1             1      1
8   CP4_N100           1             0      1
9    Fz_P200           1             0      1
10  FCz_P200           1             1      1
11   Cz_P200           1             1      1
12  FC3_P200           1             0      1
13  FC4_P200           1             1      1
14   C3_P200           1             1      1
15   C4_P200           1             1      1
16  CP3_P200           1             1      1
17  CP4_P200           1             1      1
18     Fz_B0           1             0      0
19    FCz_B0           1             0      0
20     Cz_B0           0             0      0
21    FC3_B0           1             0      0
22    FC4_B0           1             0      0
23     C3_B0           0             0      0
24     C4_B0           0             0      0
25    CP3_B0           1             1      0
26    CP4_B0           0             0      0
27     Fz_B1           0             0      1
28    FCz_B1           1             0      1
29     Cz_B1           1             0      1
30    FC3_B1           1             0      1
31    FC4_B1           0             0      1
32     C3_B1           1             0      0
33     C4_B1           0             0      1
34    CP3_B1           1             0      1
35    CP4_B1           0             0      0

### Variable Selection using Random Forest

In [72]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

rfmod = RandomForestClassifier().fit(X, y)
#rfmod.feature_importances_

array([0.02834502, 0.03024148, 0.0332528 , 0.03549979, 0.03282663,
       0.04223439, 0.0288094 , 0.02909853, 0.02752009, 0.02739337,
       0.02886493, 0.03121364, 0.02608021, 0.03046611, 0.02777875,
       0.03184972, 0.02790326, 0.02787925, 0.02567494, 0.02638896,
       0.02506343, 0.02626741, 0.0235584 , 0.02635508, 0.02396007,
       0.02803397, 0.02544133, 0.02439668, 0.02472115, 0.0239388 ,
       0.02528784, 0.0253146 , 0.02488563, 0.02384727, 0.02455708,
       0.02505   ])

In [88]:
model = SelectFromModel(rfmod, prefit=True)
model.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True, False,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False])

In [91]:
varSel['RandomForest'] = model.get_support().astype('int64')
varSel

    Variable  Univarable  RandomForest
0    Fz_N100           1             1
1   FCz_N100           1             1
2    Cz_N100           1             1
3   FC3_N100           1             1
4   FC4_N100           1             1
5    C3_N100           1             1
6    C4_N100           1             1
7   CP3_N100           1             1
8   CP4_N100           1             0
9    Fz_P200           1             0
10  FCz_P200           1             1
11   Cz_P200           1             1
12  FC3_P200           1             0
13  FC4_P200           1             1
14   C3_P200           1             1
15   C4_P200           1             1
16  CP3_P200           1             1
17  CP4_P200           1             1
18     Fz_B0           1             0
19    FCz_B0           1             0
20     Cz_B0           0             0
21    FC3_B0           1             0
22    FC4_B0           1             0
23     C3_B0           0             0
24     C4_B0           0             0
25    CP3_B0           1             1
26    CP4_B0           0             0
27     Fz_B1           0             0
28    FCz_B1           1             0
29     Cz_B1           1             0
30    FC3_B1           1             0
31    FC4_B1           0             0
32     C3_B1           1             0
33     C4_B1           0             0
34    CP3_B1           1             0
35    CP4_B1           0             0

### Variable Selection using Gradient Boosting classification

In [101]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.feature_selection import SelectFromModel

gbmod = GradientBoostingClassifier().fit(X, y)

In [102]:
model = SelectFromModel(gbmod, prefit=True)
model.get_support()

array([ True, False, False, False,  True,  True,  True, False,  True,
       False, False, False, False,  True,  True,  True, False, False,
       False,  True,  True, False, False, False, False,  True, False,
        True, False,  True,  True, False, False, False, False,  True])

In [103]:
varSel['GradientBoost'] = model.get_support().astype('int64')
varSel

    Variable  Univarable  RandomForest  Lasso  GradientBoost
0    Fz_N100           1             1      1              1
1   FCz_N100           1             1      0              0
2    Cz_N100           1             1      1              0
3   FC3_N100           1             1      1              0
4   FC4_N100           1             1      1              1
5    C3_N100           1             1      1              1
6    C4_N100           1             1      1              1
7   CP3_N100           1             1      1              0
8   CP4_N100           1             0      1              1
9    Fz_P200           1             0      1              0
10  FCz_P200           1             1      1              0
11   Cz_P200           1             1      1              0
12  FC3_P200           1             0      1              0
13  FC4_P200           1             1      1              1
14   C3_P200           1             1      1              1
15   C4_P200           1             1      1              1
16  CP3_P200           1             1      1              0
17  CP4_P200           1             1      1              0
18     Fz_B0           1             0      0              0
19    FCz_B0           1             0      0              1
20     Cz_B0           0             0      0              1
21    FC3_B0           1             0      0              0
22    FC4_B0           1             0      0              0
23     C3_B0           0             0      0              0
24     C4_B0           0             0      0              0
25    CP3_B0           1             1      0              1
26    CP4_B0           0             0      0              0
27     Fz_B1           0             0      1              1
28    FCz_B1           1             0      1              0
29     Cz_B1           1             0      1              1
30    FC3_B1           1             0      1              1
31    FC4_B1           0             0      1              0
32     C3_B1           1             0      0              0
33     C4_B1           0             0      1              0
34    CP3_B1           1             0      1              0
35    CP4_B1           0             0      0              1

### Variable Selection using SVM classification

In [109]:
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel

svmmod = LinearSVC(C=0.01, penalty="l1",dual=False).fit(X, y)

In [110]:
model = SelectFromModel(svmmod, prefit=True)
model.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [111]:
varSel['SVM'] = model.get_support().astype('int64')
varSel

    Variable  Univarable  RandomForest  Lasso  GradientBoost  SVM
0    Fz_N100           1             1      1              1    1
1   FCz_N100           1             1      0              0    1
2    Cz_N100           1             1      1              0    1
3   FC3_N100           1             1      1              0    1
4   FC4_N100           1             1      1              1    1
5    C3_N100           1             1      1              1    1
6    C4_N100           1             1      1              1    1
7   CP3_N100           1             1      1              0    1
8   CP4_N100           1             0      1              1    1
9    Fz_P200           1             0      1              0    1
10  FCz_P200           1             1      1              0    1
11   Cz_P200           1             1      1              0    1
12  FC3_P200           1             0      1              0    1
13  FC4_P200           1             1      1              1    1
14   C3_P200           1             1      1              1    1
15   C4_P200           1             1      1              1    1
16  CP3_P200           1             1      1              0    1
17  CP4_P200           1             1      1              0    1
18     Fz_B0           1             0      0              0    0
19    FCz_B0           1             0      0              1    1
20     Cz_B0           0             0      0              1    0
21    FC3_B0           1             0      0              0    0
22    FC4_B0           1             0      0              0    0
23     C3_B0           0             0      0              0    0
24     C4_B0           0             0      0              0    0
25    CP3_B0           1             1      0              1    0
26    CP4_B0           0             0      0              0    0
27     Fz_B1           0             0      1              1    1
28    FCz_B1           1             0      1              0    1
29     Cz_B1           1             0      1              1    1
30    FC3_B1           1             0      1              1    1
31    FC4_B1           0             0      1              0    1
32     C3_B1           1             0      0              0    1
33     C4_B1           0             0      1              0    1
34    CP3_B1           1             0      1              0    1
35    CP4_B1           0             0      0              1    1

### Summarization and Selection of Variables

In [120]:
varSel['Sum'] =  np.sum(varSel,axis=1)
varSel

    Variable  Univarable  RandomForest  Lasso  GradientBoost  SVM  Sum  sum
0    Fz_N100           1             1      1              1    1    5    0
1   FCz_N100           1             1      0              0    1    3    0
2    Cz_N100           1             1      1              0    1    4    0
3   FC3_N100           1             1      1              0    1    4    0
4   FC4_N100           1             1      1              1    1    5    0
5    C3_N100           1             1      1              1    1    5    0
6    C4_N100           1             1      1              1    1    5    0
7   CP3_N100           1             1      1              0    1    4    0
8   CP4_N100           1             0      1              1    1    4    0
9    Fz_P200           1             0      1              0    1    3    0
10  FCz_P200           1             1      1              0    1    4    0
11   Cz_P200           1             1      1              0    1    4    0
12  FC3_P200           1             0      1              0    1    3    0
13  FC4_P200           1             1      1              1    1    5    0
14   C3_P200           1             1      1              1    1    5    0
15   C4_P200           1             1      1              1    1    5    0
16  CP3_P200           1             1      1              0    1    4    0
17  CP4_P200           1             1      1              0    1    4    0
18     Fz_B0           1             0      0              0    0    1    0
19    FCz_B0           1             0      0              1    1    3    0
20     Cz_B0           0             0      0              1    0    1    0
21    FC3_B0           1             0      0              0    0    1    0
22    FC4_B0           1             0      0              0    0    1    0
23     C3_B0           0             0      0              0    0    0    0
24     C4_B0           0             0      0              0    0    0    0
25    CP3_B0           1             1      0              1    0    3    0
26    CP4_B0           0             0      0              0    0    0    0
27     Fz_B1           0             0      1              1    1    3    0
28    FCz_B1           1             0      1              0    1    3    0
29     Cz_B1           1             0      1              1    1    4    0
30    FC3_B1           1             0      1              1    1    4    0
31    FC4_B1           0             0      1              0    1    2    0
32     C3_B1           1             0      0              0    1    2    0
33     C4_B1           0             0      1              0    1    2    0
34    CP3_B1           1             0      1              0    1    3    0
35    CP4_B1           0             0      0              1    1    2    0

In [133]:
varSel.groupby('Sum')['Variable'].count()

Sum
0     3
1     4
2     4
3     8
4    10
5     7
Name: Variable, dtype: int64

We can now decide a threshold for selecting our variables!